### ISSUE TITLE
WHMCS Module Issue

### ISSUE THREAD

**Issue by ghost** [pelican-dev/whmcs#6]
Hi,

I am trying to deploy a server through whmcs and i am getting the following error and for the life of me i can't work out what it is.

> Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => ValidationException
                    [status] => 422
                    [detail] => The deploy.tags field must be present.
                    [meta] => Array
                        (
                            [source_field] => deploy.tags
                            [rule] => present
                        )

                )

        )

    [status_code] => 422
)

Any help would greatly be appreciated

**Comment by QuintenQVD0** [comment]
https://github.com/pelican-dev/whmcs/pull/4
